name: Run ESLint

on: push

jobs:
  run_eslinter_for_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: part11/package-lock.json

      - name: Install dependencies
        working-directory: ./part11
        run: npm ci

      - name: Check style
        working-directory: ./part11
        run: npm run lint